# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %> 
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %> 
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %> 
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %> 
  domain_name: catalinboruga.com
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 2199ea658fea723dbe64c70fa38041741739da310bfc2563c5bf2314b528dc370ce0bea52a191f1b41fff6e50a7e67abe175488b772cb8aeb471203a9845a15a

test:
  secret_key_base: 0c79940b3973660ad8162c5e5434a245e1d887213c8e42ba7b22a99724ccfcf7851483a7c6b8489809621a7ad1c944b599b18037f428ae55cb2227d137570431

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  mail_provider_username: <%= ENV["GMAIL_USERNAME"] %> 
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %> 
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %> 
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  owner_email: <%= ENV["OWNER_EMAIL"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
